### PR TITLE
final release push

### PR DESCRIPTION
**Pull request by MaximilianSeewald**

### CODE REVIEW

**Review by goetzmat — APPROVED** [review]
FINAL RELEASE PUSH
Review by:
Working: [X]
Documentation: [X]
Clean code:  [X]

**Review by goetzmat — APPROVED** [review]
FINAL RELEASE PUSH
Review by:
Working: [X]
Documentation: [X]
Clean code: [X]

**Review by PLACEBOBRO — APPROVED** [review]
[FEATURE]
Feature: All working
Created by: @MaximilianSeewald 
Review by: @PLACEBOBRO 
Working: [x]
Documentation: [x]
Clean code:  [x]
Notes:/

**Review by RealWhimsy — APPROVED** [review]
[RELEASE]
Feature: Main Release
Created by: @MaximilianSeewald @PLACEBOBRO @goetzmat @RealWhimsy 
Review by: @RealWhimsy 
Working: Yes
Documentation: Sufficient
Clean code:  Yes
Notes: Works nicely

**Pull request merged**
